# Generated by Django 5.1.5 on 2025-01-26 13:41

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import non_register.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('reason', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Freelancer',
            fields=[
                ('userId', models.CharField(default=non_register.models.generate_freelancer_id, editable=False, max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('profilePic', models.ImageField(blank=True, null=True, upload_to='freelancer/profile_pics/')),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user_role', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('social_media', models.URLField(blank=True, null=True)),
                ('education', models.CharField(max_length=255)),
                ('certifications', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('experience', models.FloatField()),
                ('skills', models.JSONField(default=dict)),
                ('password', models.CharField(max_length=128)),
                ('projects_assigned', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('project_status', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('inprogress', 'In Progress'), ('completed', 'Completed'), ('not_started', 'Not Started')], max_length=50), blank=True, default=list, size=None)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('currently_working', models.BooleanField(default=False)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_history', to='non_register.freelancer')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_name', models.CharField(max_length=255)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('certification_id', models.CharField(max_length=100, unique=True)),
                ('certification_url', models.URLField(blank=True, null=True)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='non_register.freelancer')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('experience_years', models.PositiveIntegerField()),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_set', to='non_register.freelancer')),
            ],
        ),
    ]
