# Generated by Django 5.1.5 on 2025-02-03 12:59

import non_register.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.CharField(default=non_register.models.generate_contact_id, max_length=10, primary_key=True, serialize=False)),
                ('user_type', models.CharField(default='NR', max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('reason', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
