# Generated by Django 5.1.5 on 2025-01-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('non_register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='user_role',
            field=models.CharField(default='freelancer', max_length=50),
        ),
    ]
