# Generated by Django 5.1.5 on 2025-02-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('non_register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='user_type',
            field=models.CharField(default='Non_register', max_length=50),
        ),
    ]
