# Generated by Django 5.1.5 on 2025-02-05 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('non_register', '0002_alter_contact_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='user_id',
            field=models.CharField(default='NR00001', max_length=20),
        ),
    ]
