# Generated by Django 5.1.5 on 2025-01-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('non_register', '0003_alter_freelancer_certifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='experience_years',
            field=models.FloatField(),
        ),
    ]
