# Generated by Django 5.1.5 on 2025-01-28 07:04

import non_register.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('non_register', '0004_alter_skill_experience_years'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectsDisplay',
            fields=[
                ('opportunityId', models.CharField(default=non_register.models.generate_opportunity_id, editable=False, max_length=12, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('budget', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('time_zone', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('project_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('deliverables', models.TextField()),
                ('requirements', models.TextField()),
                ('challenges', models.TextField()),
                ('skills_required', models.CharField(max_length=255)),
            ],
        ),
    ]
