# Generated by Django 5.1.5 on 2025-01-29 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('non_register', '0006_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
