# Generated by Django 5.1.5 on 2025-02-12 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_schemas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectquote',
            name='client',
            field=models.ForeignKey(default='CL86254975', on_delete=django.db.models.deletion.CASCADE, to='db_schemas.client'),
        ),
        migrations.AddField(
            model_name='projectstatusdetails',
            name='admin',
            field=models.CharField(default='AD001', max_length=20),
        ),
        migrations.AddField(
            model_name='projectstatusdetails',
            name='client',
            field=models.ForeignKey(default='CL86254975', on_delete=django.db.models.deletion.CASCADE, to='db_schemas.client'),
        ),
        migrations.AlterField(
            model_name='client',
            name='profilePic',
            field=models.ImageField(blank=True, default='client/profile_pics/default_profile.png', null=True, upload_to='client/profile_pics/'),
        ),
    ]
