# Generated by Django 5.1.5 on 2025-02-12 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_schemas', '0002_projectquote_client_projectstatusdetails_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsdisplay',
            name='client',
            field=models.ForeignKey(default='CL86254975', on_delete=django.db.models.deletion.CASCADE, to='db_schemas.client'),
        ),
    ]
