# Generated by Django 5.1.5 on 2025-02-13 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_schemas', '0003_projectsdisplay_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectquote',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_schemas.client'),
        ),
        migrations.AlterField(
            model_name='projectsdisplay',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_schemas.client'),
        ),
        migrations.AlterField(
            model_name='projectstatusdetails',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_schemas.client'),
        ),
    ]
