# Generated by Django 5.1.5 on 2025-02-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_schemas', '0006_projectquote_admin_margin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectquote',
            old_name='bid_status',
            new_name='admin_bid_status',
        ),
        migrations.AddField(
            model_name='projectquote',
            name='client_bid_status',
            field=models.CharField(default='Not confrimed yet', max_length=20),
        ),
    ]
