# Generated by Django 5.1.5 on 2025-02-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_schemas', '0007_rename_bid_status_projectquote_admin_bid_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectquote',
            name='admin_bid_status',
            field=models.CharField(default='Not confirmed yet', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectquote',
            name='client_bid_status',
            field=models.CharField(default='Not confirmed yet', max_length=20),
        ),
    ]
