# Generated by Django 5.1.5 on 2025-02-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_schemas', '0008_alter_projectquote_admin_bid_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectquote',
            name='revised_budget',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
