# Generated by Django 5.1.5 on 2025-02-06 08:42

import django.db.models.deletion
import django.utils.timezone
import freelancer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Freelancer',
            fields=[
                ('userId', models.CharField(default=freelancer.models.generate_freelancer_id, editable=False, max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user_role', models.CharField(default='freelancer', max_length=50)),
                ('profile_summary', models.TextField(blank=True, max_length=512, null=True)),
                ('designation', models.CharField(max_length=50)),
                ('social_media', models.URLField(blank=True, null=True)),
                ('country', models.CharField(max_length=50)),
                ('education', models.CharField(max_length=255)),
                ('certifications', models.CharField(blank=True, max_length=255, null=True)),
                ('experience', models.FloatField()),
                ('skills', models.JSONField(default=dict)),
                ('projects_assigned', models.CharField(blank=True, max_length=255)),
                ('project_status', models.CharField(blank=True, max_length=50)),
                ('profilePic', models.ImageField(blank=True, null=True, upload_to='freelancer/profile_pics/')),
                ('password', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectsDisplay',
            fields=[
                ('opportunityId', models.CharField(default=freelancer.models.generate_opportunity_id, editable=False, max_length=12, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('budget', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('time_zone', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('project_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('deliverables', models.TextField()),
                ('requirements', models.TextField()),
                ('challenges', models.TextField()),
                ('skills_required', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('currently_working', models.BooleanField(default=False)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_history', to='freelancer.freelancer')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_name', models.CharField(max_length=255)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('certification_id', models.CharField(max_length=100, unique=True)),
                ('certification_url', models.URLField(blank=True, null=True)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='freelancer.freelancer')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectQuote',
            fields=[
                ('projectQuoteId', models.CharField(default=freelancer.models.generate_projectquote_id, editable=False, max_length=12, primary_key=True, serialize=False)),
                ('opportunityId', models.CharField(max_length=20)),
                ('budget', models.CharField(max_length=20)),
                ('time_estimation', models.CharField(max_length=20)),
                ('comments', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelancer.freelancer')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('experience_years', models.FloatField()),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_set', to='freelancer.freelancer')),
            ],
        ),
    ]
