# Generated by Django 5.1.5 on 2025-01-30 09:57

import freelancer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('reason', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectsDisplay',
            fields=[
                ('opportunityId', models.CharField(default=freelancer.models.generate_opportunity_id, editable=False, max_length=12, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('budget', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('time_zone', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('project_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('deliverables', models.TextField()),
                ('requirements', models.TextField()),
                ('challenges', models.TextField()),
                ('skills_required', models.CharField(max_length=255)),
            ],
        ),
    ]
