# Generated by Django 5.1.5 on 2025-02-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0002_certificate_created_at_certificate_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certification_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
