# Generated by Django 5.1.5 on 2025-02-03 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0003_freelancer_employmenthistory_certificate_skill'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
