# Generated by Django 5.1.5 on 2025-02-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0003_alter_certificate_certification_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='profilePic',
            field=models.ImageField(blank=True, default='freelancer/profile_pics/default_profile.png', null=True, upload_to='freelancer/profile_pics/'),
        ),
    ]
