# Generated by Django 5.1.5 on 2025-02-04 13:00

import freelancer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0005_alter_freelancer_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectQuote',
            fields=[
                ('projectQuoteId', models.CharField(default=freelancer.models.generate_projectquote_id, editable=False, max_length=12, primary_key=True, serialize=False)),
                ('freelancer', models.CharField(max_length=20)),
                ('opportunityId', models.CharField(max_length=20)),
                ('budget', models.CharField(max_length=20)),
                ('time_estimation', models.CharField(max_length=20)),
                ('comments', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
