# Generated by Django 5.1.5 on 2025-02-04 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0006_projectquote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectquote',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelancer.freelancer'),
        ),
    ]
