# Generated by Django 5.1.4 on 2025-01-15 04:40

import django.contrib.postgres.fields
import django.utils.timezone
import recruiter.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('userId', models.CharField(default=recruiter.models.generate_recruiter_id, editable=False, max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('profilePic', models.ImageField(blank=True, null=True, upload_to='recruiter/profile_pics/')),
                ('phone_number', models.BigIntegerField()),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('user_role', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('job_portal_links', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, default=list, size=None)),
                ('designation', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=255)),
                ('unique_organization_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('opportunity_id', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('password', models.CharField(max_length=128)),
                ('project_status', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('inprogress', 'In Progress'), ('completed', 'Completed'), ('not_started', 'Not Started')], max_length=50), blank=True, default=list, size=None)),
                ('joining_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
