# Generated by Django 5.1.4 on 2025-01-16 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('non_register', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='freelancer',
        ),
        migrations.DeleteModel(
            name='Freelancer',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
